### ISSUE TITLE
Youtilube Music Support

### ISSUE THREAD

**Issue by samnewman86** [miikkajo/hassio_addons#1]
Google music is gradually moving across to YouTube music, is support available for YouTube music accounts?

**Comment by miikkajo** [comment]
This project is build entirely on unoffical gmusicapi 
https://unofficial-google-music-api.readthedocs.io/en/latest/ 

as it's build on unoffical api, no promises can be made.
as far as i know gmusicapi only supports google music endpoints.

there is some discussion available on project github issue

https://github.com/simon-weber/gmusicapi/issues/609
